# Generated by Django 5.1.2 on 2024-10-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='user',
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user_id',
            field=models.UUIDField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
