# Generated by Django 5.1.2 on 2024-11-04 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_rename_uuid_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=40)),
                ('question_text', models.TextField()),
                ('choice1', models.CharField(max_length=40)),
                ('choice2', models.CharField(max_length=40)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Answer',
            fields=[
                ('answer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_choice', models.CharField(choices=[('1', 'choice1'), ('2', 'choice2')], max_length=1)),
                ('choice_reason', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
