# Generated by Django 5.1.2 on 2024-11-07 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
