# Generated by Django 5.1.2 on 2024-11-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_user_answer_answer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_answer',
            name='answer_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
